version: '3.4'

services:
  aeonserver:
    image: ${DOCKER_REGISTRY-}aeonserver
    ports:
      - 2366:2366
      - 2363:2363
    build:
      context: .
      dockerfile: AeonServer/Dockerfile
    depends_on:
      - auth

  auth:
    image: postgres
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: tupotrof
      POSTGRES_PASSWORD: otstoynik