CREATE TABLE [dbo].[Games]
(
	[ID] INT NOT NULL PRIMARY KEY Identity, 
    [Player1ID] INT NOT NULL FOREIGN KEY REFERENCES Players([ID]), 
    [Player2ID] INT NOT NULL FOREIGN KEY REFERENCES Players([ID]), 
    [Hero1] SMALLINT NOT NULL FOREIGN KEY REFERENCES Heroes([ID]), 
    [Hero2] SMALLINT NOT NULL FOREIGN KEY REFERENCES Heroes([ID]), 
    [Winner] TINYINT NULL, 
)
